name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  dio: ^5.7.0
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  get_it: ^8.0.3
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  bloc: ^9.0.0
  shared_preferences: ^2.5.1
  hive: ^2.2.3
  path_provider: ^2.1.5
  hive_generator: ^2.0.1
  envied: ^1.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  retrofit_generator: '>=8.0.0 <10.0.0' # for Dart 3.3 use ^9.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.8.0
  flutter_gen_runner: ^5.9.0
  envied_generator: ^1.1.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/spotify.png
    - assets/images/spotify_gray.png

